### ISSUE TITLE
ngio for fractal-tasks-core: Overview

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#850]
This issue is meant as an overview for the effort to transition fractal-tasks-core to use ngio.

The overall strategy is:
1. Add an ngio dependency to fractal-tasks-core
2. Start using ngio in different tasks until all tasks depend on ngio for OME-Zarr reading & writing, label reading & writing & table reading & writing
3. Deprecate the respective library functions in fractal-tasks-core
4. Release a fractal-tasks-core 2.0.0 version where we remove those library functions

----------

Nomenclature below: Top-level TODOs are the tasks. Fix sub-items are must fix issues in the task: We want to see that the ngio refactor fixes this issue. Review sub-items are minor issues we may be able to tackle during the refactor.

# Tasks to transition to using ngio:

Converters
- [ ] Convert Cellvoyager to OME-Zarr
    - [ ] Review https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/843
    - [ ] Review https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/823
- [ ] Convert Cellvoyager Multiplexing to OME-Zarr
    - [ ] Review https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/843
    - [ ] Review https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/845
    - [ ] Review https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/819

Tasks that write new OME-Zarr images
- [ ] Project Image (HCS Plate): in https://github.com/fractal-analytics-platform/fractal-tasks-core/blob/main/fractal_tasks_core/tasks/projection.py
    - [ ] Fix https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/840
    - [ ] Review https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/841 
    - [ ] Review https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/823
    - [ ] Replace use of `NgffImageMeta` usage with ngio (`load_NgffImageMeta`)
    - [ ] Replace direct zarr operations (zarr.open_group etc.) with ngio
    - [ ] Replace dask operations for array access with ngio
    - [ ] Replace writing operations with ngio
    - [ ] Replace pyramid building with ngio
- [ ] Illumination Correction
- [ ] Apply Registration to Image
    - [ ] Replace use of `NgffImageMeta` usage with ngio (`load_NgffImageMeta`)
    - [ ] In `write_registered_zarr`, replace metadata access & image loading & writing with ngio
    - [ ] In `write_registered_zarr`, replace pyramid building with ngio

Tasks that write tables
- [ ] Calculate Registration (image-based)
- [ ] Find Registration Consensus

Other tasks:

- [ ] Import OME-Zarr
    - [ ] In `_process_single_image`: Replace use of `NgffImageMeta` usage with ngio
    - [ ] In `_process_single_image`: Replace ROI copying & table writing functionality with ngio

Not a goal for the moment: Handle the well & plate metadata with ngio

# Currently blocked because we're waiting for feature X in ngio

### Waiting for masking ROI writing

- [ ] Cellpose Segmentation
    - [ ] Fix https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/787
    - [ ] Review https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/742

# Task with other goals

- [ ] Napari Workflows Wrapper
    - [ ] Move napari workflows task into its own repo: https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/849
    - [ ] Add a simpler scikit-image based measurement task to the fractal-tasks-core repo
    - [ ] Move these issue to new napari workflows repo: 
        - [ ] https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/411
        - [ ] https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/356
        - [ ] https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/352
        - [ ] https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/349
        - [ ] https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/186
        - [ ] https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/183
        - [ ] https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/181

# Additional issues:

- [ ] Review https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/833 & https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/463
- [ ] Test e.g. in the Cellpose task that label upsampling of a masking label image works when the dimensions don't easily match: https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/771
- [ ] Review that table copying in illumination correction, apply registration etc. are now all using ngio features for this: https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/725
- [ ] Review https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/681
- [ ] Review that we're not sensitive to trailing slashes in zarr_urls anymore: https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/677 (maybe still an issue in some fractal-tasks-core helper functions?)
- [ ] Review how ROI tables & their indices now look: https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/672
- [ ] Test core tasks with OME-Zarrs that have singleton T dimensions: https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/663
- [ ] Review that try-except error handling for Zarr operations has been moved into ngio: https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/541
- [ ] Review that tasks support actual workflows with time data (e.g. run cellpose & measurements across all timepoints of an existing OME-Zarr with timepoints): https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/169
- [ ] How are we handling global scale transformations in ngio? https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/50

# Deprecate

- [ ] Deprecate `prepare_label_group`: https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/634
- [ ] Deprecate `is_ROI_table_valid`: https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/633
- [ ] Deprecate `get_pixel_sizes_zyx`: https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/577

# Issues Joel needs to review further
Not sure yet what exactly is needed now to close these issues

- [ ] https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/448
- [ ] Review that the masked loading now fulfills requirements described here: https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/340
- [ ] Review mixed dimensionality support requirements: https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/150

-----

Issues related to ngio that should get tackled later (e.g. after 2.0.0 release):
- Parallel processing of ROIs within tasks: https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/44
- Parallelize illumination correction across channels: https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/687 (either within the task or across a compound task)

**Comment by jluethi** [comment]
I think adoption of new task tools can target the v2 branch. Let's coordinate at the call today, Lorenzo is also working on that branch now.
