### ISSUE TITLE
Integration test

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#88]
As of our last meeting today:

Let's add an integration test which runs on a small dataset (I would aim at something like 2 wells of 2x2 sites, with just a couple of Z levels and a handful channels). The plan is to run `yokogawa_to-zarr` + `illumination_correction` + `maximum_intensity_projection`, and then to compare the three zarr files with reference ones.

Some more work is probably needed before adding this test becomes compelling. At least on these issues:
- [x] Complete the first version of the illumination-correction task (with custom selection of correction images), https://github.com/fractal-analytics-platform/mwe_fractal/issues/62.
- [x] Sort out the channel assignment, https://github.com/fractal-analytics-platform/mwe_fractal/issues/61.
- [ ] Reach some stability in the way a workflow is defined, related to the "pipeline file" which we should discuss in https://github.com/fractal-analytics-platform/mwe_fractal/issues/68.

**Comment by tcompa** [comment]
Close in favor of #2 (which will be closed by #90)
